# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 500)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_reset_place = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset_place.setObjectName("btn_reset_place")
        self.gridLayout.addWidget(self.btn_reset_place, 0, 2, 1, 1)
        self.input_place_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_place_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input_place_name.setStatusTip("")
        self.input_place_name.setObjectName("input_place_name")
        self.gridLayout.addWidget(self.input_place_name, 0, 1, 1, 1)
        self.btn_search_place = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search_place.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_search_place.setAcceptDrops(False)
        self.btn_search_place.setObjectName("btn_search_place")
        self.gridLayout.addWidget(self.btn_search_place, 0, 3, 1, 1)
        self.comboBox_map_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_map_type.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_map_type.setAcceptDrops(False)
        self.comboBox_map_type.setObjectName("comboBox_map_type")
        self.comboBox_map_type.addItem("")
        self.comboBox_map_type.addItem("")
        self.comboBox_map_type.addItem("")
        self.gridLayout.addWidget(self.comboBox_map_type, 0, 0, 1, 1)
        self.map_pic = QtWidgets.QLabel(self.centralwidget)
        self.map_pic.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.map_pic.setText("")
        self.map_pic.setObjectName("map_pic")
        self.gridLayout.addWidget(self.map_pic, 3, 0, 1, 4)
        self.obj_address = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.obj_address.setObjectName("obj_address")
        self.gridLayout.addWidget(self.obj_address, 1, 0, 1, 3)
        self.check_index = QtWidgets.QCheckBox(self.centralwidget)
        self.check_index.setObjectName("check_index")
        self.gridLayout.addWidget(self.check_index, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BigTask MapAPI"))
        self.btn_reset_place.setText(_translate("MainWindow", "Сброс"))
        self.input_place_name.setToolTip(_translate("MainWindow", "Введите адрес объекта для поиска"))
        self.btn_search_place.setText(_translate("MainWindow", "Искать"))
        self.comboBox_map_type.setItemText(0, _translate("MainWindow", "карта"))
        self.comboBox_map_type.setItemText(1, _translate("MainWindow", "спутник"))
        self.comboBox_map_type.setItemText(2, _translate("MainWindow", "гибрид"))
        self.check_index.setText(_translate("MainWindow", "Индекс"))
